/*==============================================================*/
/* SISTEMA: Pedido de Venda                                     */
/* BANCO:   Firebird 3.0+                                       */
/* CRIADO:  2026-05-14                                          */
/*==============================================================*/


/*==============================================================*/
/* SEQUENCES (Generators)                                       */
/*==============================================================*/

CREATE SEQUENCE SEQ_PEDIDO;
ALTER SEQUENCE SEQ_PEDIDO RESTART WITH 1;


/*==============================================================*/
/* TABELA: CLIENTE                                              */
/*==============================================================*/

-- não definido sequence e trigger pois não haverá cadastro pelo sistema
-- os dados serão inseridos mais abaixo nesse script apenas para teste
CREATE TABLE CLIENTE (
    CODIGO   INTEGER      NOT NULL,
    NOME     VARCHAR(127) NOT NULL,
    CIDADE   VARCHAR(127) NOT NULL,
    UF       CHAR(2)      NOT NULL,
    CONSTRAINT PK_CLIENTE PRIMARY KEY (CODIGO)
);


/*==============================================================*/
/* TABELA: PRODUTO                                              */
/*==============================================================*/

-- não definido sequence e trigger pois não haverá cadastro pelo sistema
-- os dados serão inseridos mais abaixo nesse script apenas para teste
CREATE TABLE PRODUTO (
    CODIGO      INTEGER       NOT NULL,
    DESCRICAO   VARCHAR(127)  NOT NULL,
    PRECO_VENDA NUMERIC(15,2) DEFAULT 0 NOT NULL,
    CONSTRAINT PK_PRODUTO PRIMARY KEY (CODIGO)
);


/*==============================================================*/
/* TABELA: PEDIDO                                               */
/*==============================================================*/

CREATE TABLE PEDIDO (
    NUMERO_PEDIDO  INTEGER       NOT NULL,
    DATA_EMISSAO   DATE          DEFAULT CURRENT_DATE NOT NULL,
    CODIGO_CLIENTE INTEGER       NOT NULL,
    VALOR_TOTAL    NUMERIC(15,2) DEFAULT 0 NOT NULL,
    CONSTRAINT PK_PEDIDO PRIMARY KEY (NUMERO_PEDIDO),
    CONSTRAINT FK_PEDIDO_CLIENTE FOREIGN KEY (CODIGO_CLIENTE)
        REFERENCES CLIENTE (CODIGO)
);


/*==============================================================*/
/* TABELA: PEDIDO_ITEM                                          */
/*==============================================================*/

-- aqui usando identity column ao invés de sequence e trigger
-- devido ao requisito do desafio:
-- "PEDIDO_ITEM.ID deve ser auto incremento (Identity/Generator)."
CREATE TABLE PEDIDO_ITEM (
    ID             INTEGER       GENERATED BY DEFAULT AS IDENTITY,
    NUMERO_PEDIDO  INTEGER       NOT NULL,
    CODIGO_PRODUTO INTEGER       NOT NULL,
    QUANTIDADE     NUMERIC(15,4) DEFAULT 0 NOT NULL,
    VLR_UNITARIO   NUMERIC(15,2) DEFAULT 0 NOT NULL,
    VLR_TOTAL      NUMERIC(15,2) DEFAULT 0 NOT NULL,
    CONSTRAINT PK_PEDIDO_ITEM PRIMARY KEY (ID),
    CONSTRAINT FK_PEDIDO_ITEM_PEDIDO FOREIGN KEY (NUMERO_PEDIDO)
        REFERENCES PEDIDO (NUMERO_PEDIDO),
    CONSTRAINT FK_PEDIDO_ITEM_PRODUTO FOREIGN KEY (CODIGO_PRODUTO)
        REFERENCES PRODUTO (CODIGO)
);


/*==============================================================*/
/* ÍNDICES                                                      */
/*==============================================================*/

/* Obrigatórios */
CREATE INDEX IDX_PEDIDO_CLIENTE
    ON PEDIDO (CODIGO_CLIENTE);

CREATE INDEX IDX_PEDIDO_ITEM_PEDIDO
    ON PEDIDO_ITEM (NUMERO_PEDIDO);

/* Opcional (recomendado) */
CREATE INDEX IDX_PEDIDO_ITEM_PRODUTO
    ON PEDIDO_ITEM (CODIGO_PRODUTO);


/*==============================================================*/
/* TRIGGERS — Auto incremento via Sequence                      */
/*==============================================================*/

SET TERM ^ ;

CREATE OR ALTER TRIGGER TRG_PEDIDO_BI
    FOR PEDIDO
    ACTIVE BEFORE INSERT
    POSITION 0
AS
BEGIN
    IF (NEW.NUMERO_PEDIDO IS NULL OR NEW.NUMERO_PEDIDO = 0) THEN
        NEW.NUMERO_PEDIDO = NEXT VALUE FOR SEQ_PEDIDO;
END^

SET TERM ; ^


/*==============================================================*/
/* CARGA DE DADOS — CLIENTE (10 registros)                      */
/*==============================================================*/

INSERT INTO CLIENTE (CODIGO, NOME, CIDADE, UF) VALUES (1,  'Empresa Alpha Ltda',           'São Paulo',        'SP');
INSERT INTO CLIENTE (CODIGO, NOME, CIDADE, UF) VALUES (2,  'Comércio Beta S/A',            'Rio de Janeiro',   'RJ');
INSERT INTO CLIENTE (CODIGO, NOME, CIDADE, UF) VALUES (3,  'Distribuidora Gama ME',        'Belo Horizonte',   'MG');
INSERT INTO CLIENTE (CODIGO, NOME, CIDADE, UF) VALUES (4,  'Indústria Delta Eireli',       'Curitiba',         'PR');
INSERT INTO CLIENTE (CODIGO, NOME, CIDADE, UF) VALUES (5,  'Atacado Épsilon Ltda',         'Porto Alegre',     'RS');
INSERT INTO CLIENTE (CODIGO, NOME, CIDADE, UF) VALUES (6,  'Varejista Zeta ME',            'Salvador',         'BA');
INSERT INTO CLIENTE (CODIGO, NOME, CIDADE, UF) VALUES (7,  'Transportes Eta S/A',          'Fortaleza',        'CE');
INSERT INTO CLIENTE (CODIGO, NOME, CIDADE, UF) VALUES (8,  'Construtora Theta Ltda',       'Manaus',           'AM');
INSERT INTO CLIENTE (CODIGO, NOME, CIDADE, UF) VALUES (9,  'Agropecuária Iota Eireli',     'Goiânia',          'GO');
INSERT INTO CLIENTE (CODIGO, NOME, CIDADE, UF) VALUES (10, 'Tecnologia Kappa ME',          'Florianópolis',    'SC');


/*==============================================================*/
/* CARGA DE DADOS — PRODUTO (10 registros)                      */
/*==============================================================*/

INSERT INTO PRODUTO (CODIGO, DESCRICAO, PRECO_VENDA) VALUES (1,  'Notebook Dell Inspiron 15',      3599.90);
INSERT INTO PRODUTO (CODIGO, DESCRICAO, PRECO_VENDA) VALUES (2,  'Monitor LG 24" Full HD',          899.00);
INSERT INTO PRODUTO (CODIGO, DESCRICAO, PRECO_VENDA) VALUES (3,  'Teclado Mecânico Redragon',       299.90);
INSERT INTO PRODUTO (CODIGO, DESCRICAO, PRECO_VENDA) VALUES (4,  'Mouse Logitech MX Master 3',      449.00);
INSERT INTO PRODUTO (CODIGO, DESCRICAO, PRECO_VENDA) VALUES (5,  'Headset HyperX Cloud II',         379.90);
INSERT INTO PRODUTO (CODIGO, DESCRICAO, PRECO_VENDA) VALUES (6,  'SSD Kingston 480GB SATA',         219.00);
INSERT INTO PRODUTO (CODIGO, DESCRICAO, PRECO_VENDA) VALUES (7,  'Memória RAM 16GB DDR4 Kingston',  289.90);
INSERT INTO PRODUTO (CODIGO, DESCRICAO, PRECO_VENDA) VALUES (8,  'Webcam Logitech C920 HD',         399.00);
INSERT INTO PRODUTO (CODIGO, DESCRICAO, PRECO_VENDA) VALUES (9,  'Nobreak APC 700VA',               459.90);
INSERT INTO PRODUTO (CODIGO, DESCRICAO, PRECO_VENDA) VALUES (10, 'Cabo HDMI 2.0 2m Multilaser',      39.90);


/*==============================================================*/
/* COMMIT                                                       */
/*==============================================================*/

COMMIT;
